version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    volumes: 
      - .dbdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 54322:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
